import Link from "next/link";
import { StatusBadge } from "@/components/status-badge";
import { applicationStatusLabels, applicationStatuses } from "@/lib/constants";
import { formatDate, formatDateTime } from "@/lib/format";
import { prisma } from "@/lib/prisma";
export const dynamic = "force-dynamic";
type SearchParams = Promise<{ q?: string; status?: string; sort?: string }>;
export default async function ApplicationsPage({ searchParams }: { searchParams: SearchParams }) {
  const { q = "", status = "", sort = "newest" } = await searchParams;
  const statusFilter = status === "active" ? { status: { in: ["applied", "in_progress"] } } : status === "closed" ? { status: { in: ["rejected", "withdrawn"] } } : applicationStatuses.includes(status as typeof applicationStatuses[number]) ? { status } : {};
  const where = { ...(q ? { OR: [{ company: { contains: q } }, { jobTitle: { contains: q } }] } : {}), ...statusFilter };
  const applications = await prisma.application.findMany({ where, include: { stages: { where: { scheduledAt: { not: null }, status: { notIn: ["completed", "passed", "failed", "cancelled"] } }, orderBy: { scheduledAt: "asc" }, take: 1 } }, orderBy: { applicationDate: sort === "oldest" ? "asc" : "desc" } });
  return <div className="space-y-7"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-indigo-600">投递管理</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">全部投递</h1><p className="mt-2 text-sm text-slate-500">搜索、筛选并查看每一份职位申请。</p></div><Link className="button-primary" href="/applications/new">+ 新建投递</Link></section><form className="card grid gap-3 p-4 md:grid-cols-[1fr_180px_150px_auto]" action="/applications"><input className="input" name="q" defaultValue={q} placeholder="搜索公司或职位…" /><select className="input" name="status" defaultValue={status}><option value="">全部状态</option><option value="active">进行中（含已投递）</option><option value="closed">已结束</option>{applicationStatuses.map((item) => <option value={item} key={item}>{applicationStatusLabels[item]}</option>)}</select><select className="input" name="sort" defaultValue={sort}><option value="newest">投递日期：最新优先</option><option value="oldest">投递日期：最早优先</option></select><button className="button-secondary">应用筛选</button></form><div className="card overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50/60 text-xs font-medium tracking-wide text-slate-500"><tr><th className="px-5 py-3">公司</th><th className="px-5 py-3">职位</th><th className="px-5 py-3">投递日期</th><th className="px-5 py-3">当前阶段</th><th className="px-5 py-3">下个安排</th><th className="px-5 py-3">状态</th></tr></thead><tbody className="divide-y divide-slate-100">{applications.length === 0 ? <tr><td className="px-5 py-14 text-center text-slate-500" colSpan={6}>没有符合当前筛选条件的投递记录。</td></tr> : applications.map((application) => { const upcoming = application.stages[0]; return <tr className="hover:bg-slate-50" key={application.id}><td className="px-5 py-4 font-medium text-slate-900"><Link href={`/applications/${application.id}`} className="hover:text-indigo-600">{application.company}</Link></td><td className="px-5 py-4 text-slate-600">{application.jobTitle}</td><td className="px-5 py-4 text-slate-600">{formatDate(application.applicationDate)}</td><td className="px-5 py-4 text-slate-600">{upcoming?.name ?? "—"}</td><td className="px-5 py-4 text-slate-600">{upcoming?.scheduledAt ? `${upcoming.name} · ${formatDateTime(upcoming.scheduledAt)}` : "—"}</td><td className="px-5 py-4"><StatusBadge status={application.status} /></td></tr>; })}</tbody></table></div></div>;
}
